name: "Continuous Integration"
on:
  push:
    branches:
      - master
    paths-ignore:
      - README
      - LICENSE
  pull_request:
    branches:
      - master
    paths-ignore:
      - README
      - LICENSE
        
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3
        name: "Checkout" 
      - uses: actions/setup-dotnet@v3
        name: "Setup .NET Core"
        with:
          dotnet-version: |
            6.0.x
      
      - name: "Install Dependencies"
        run: dotnet restore
        
      - name: "Build"
        run: dotnet build --configuration Release --no-restore

      - name: "Test PR"
        run: |
          dotnet test --no-restore --no-build --configuration Release


        
    
  